### ISSUE TITLE
MacOS catalina Incompatible

### ISSUE THREAD

**Issue by StealthWire** [nst/CocoaSlideShow#4]
Hey! Any plans to make this compatible with MacOS Catalina compatible?

**Comment by nst** [comment]
Hey thank you for using CocoaSlideShow :) I just made a quick update http://seriot.ch/software/desktop/CocoaSlideShow/CocoaSlideShow_0_8.app.zip it should run on Catalina, although not thoroughly tested.

**Comment by StealthWire** [comment]
Hey, thanks for the update, been busy lately, will check asap and get back
to you.

**Comment by StealthWire** [comment]
Hey, works great until now! Thanks for this, really love the app!
